# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  # environment variables NODE_VERSION and YARN_VERSION set in Netlify settings UI
  base = "app/javascript"
  command = "npm install yarn && yarn install && yarn run build-storybook"
  publish = "storybook-static"
  ignore = "git diff --quiet HEAD^ HEAD ./ && git diff --quiet HEAD^ HEAD ../assets/stylesheets/config/"
[build.environment]
  NODE_VERSION = "14.14"
[[redirects]]
from = "http://storybook.dev.to"
to = "https://storybook.forem.com"
status = 301
force = true

[[redirects]]
from = "http://storybook.dev.to/*"
to = "https://storybook.forem.com/:splat"
status = 301
force = true
